# Generated by Django 2.1.2 on 2018-10-02 04:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_auto_20181001_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='people',
            field=models.ManyToManyField(related_name='involved', through='bills.Involvement', to=settings.AUTH_USER_MODEL),
        ),
    ]
