# Generated by Django 2.1.2 on 2018-10-05 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0005_auto_20181002_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='desc',
            field=models.TextField(default='No description.'),
        ),
    ]
